### ISSUE TITLE
Implement Todo List Backend:

### ISSUE THREAD

**Issue by Zapix** [Zapix/mtpylon-todo-list#10]
- [x] Create Todo List 
- [x] Read Todo List and list of Todo Lists (with pagination)
- [x] Delete Todo List
