### ISSUE TITLE
Implement Todo Item Frontend

### ISSUE THREAD

**Issue by Zapix** [Zapix/mtpylon-todo-list#13]
- [x] Create Todo Item for TodoList
- [x] Retrieve Todo Item list for TodoList
- [x] Mark Todo Item as complete/uncompleted
